### ISSUE TITLE
Questions about ProtoBuf

### ISSUE THREAD

**Issue by arrascue** [tf-dbis-uni-freiburg/PRoST#17]
1) What is the motivation of using Protobuf. Why do you need a transfer protocol? Was a regular serialization mechanism not enough?
2) Where is the schema of the protobuf objects you have created and give as input to the compiler?

**Comment by matteuan** [comment]
1) We needed to serialize between translator/loader. It was chosen to be independent from programming language, because before the loader was written in python. Personally, I already had experience with that and it was easy to set up.
2) The main proto file is [here](https://github.com/tf-dbis-uni-freiburg/PRoST/blob/master/ProtobufStats.proto) but I think it doesn't match anymore the compiled files "ProtobufStats.java". We changed with Polina 2 months ago, but we probably forgot to commit the actual proto file.

**Comment by arrascue** [comment]
@polinankoleva could you commit the proto file to close this issue?
